#!/bin/sh

SPEC_MD=node_modules/.bin/spec-md
SPECS=*/v*.*

echo > __index__.md
for spec in $SPECS; do
  echo $spec
  base=$(dirname $spec)-$(basename $spec)
  md=$spec/$base.md
  gql=$spec/$base.graphql
  if [ -e $md ]; then
    $SPEC_MD $md > $spec/index.html &
  fi
  if [ -e $gql ]; then
    ln -s $base.graphql $spec/__schema__.graphql
  fi
  echo "- **[$spec](/$spec)** ([📄 graphql]($gql))" >> __index__.md
done
wait $(jobs -p)
$SPEC_MD index.md > index.html